### ISSUE TITLE
Unable to Login 

### ISSUE THREAD

**Issue by rhnvrm** [dennislysenko/bloodhound-radio#11]
This is the error message that appears after clicking `**Login with Soundcloud** to get started`

https://screc.herokuapp.com/auth/failure?message=redirect_uri_mismatch&origin=https%3A%2F%2Fscrec.herokuapp.com%2F&strategy=soundcloud#

Also, there is a 406 response from soundcloud, for the oath request, I guess.

**Comment by dennislysenko** [comment]
Ah, unfortunate. I'm getting the same thing as well. redirect_uri_mismatch seems like it could be something trivial, will need to check though.

**Comment by dennislysenko** [comment]
Interesting. It just started working for me. @rhnvrm any update?

**Comment by rhnvrm** [comment]
Yes, it's working now.

**Comment by dennislysenko** [comment]
@rhnvrm, do you have trouble playing scents at all? When I tested yesterday, I started getting JS console errors when trying to create a scent and play tracks from it. Let me know if you have a similar issue--maybe something in the soundcloud API changed.

**Comment by rhnvrm** [comment]
I did not go past the login page. I'll test it on the weekend an list you
know.

Sincerely,
Rohan Verma
hello@rohanverma.net
